/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-03-04 00:43:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.http.HttpRequest;
import java.net.*;
import java.util.*;
import java.util.Base64.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


	public static String stringToBase64(String str) //da stringa a base64
	{
	    byte[] bytes = str.getBytes();
	    byte[] encoded = Base64.getEncoder().encode(bytes);
	    return new String(encoded);
	}
	public static String base64ToString(String base64) //da base64 a stringa
	{
	    byte[] decoded = Base64.getDecoder().decode(base64);
	    return new String(decoded);
	}
	
	public static Boolean is_logged_in(String nome)
	{
		if(nome == null) return false;
		else return true;
	}
	public static String pulisci_attributo()
	{
		return null;
	}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.util.Base64");
    _jspx_imports_packages.add("java.net");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.net.http.HttpRequest");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=US-ASCII");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<title>Titolo Pagina</title>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/style\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Boolean accesso = false; //controllo se l'utente ha fatto l'accesso
	String nome_sess = "", //dati utente
			cognome_sess ="",
			email_sess = "",
			password_sess="";
	String pagina = ""; //pagine dinamiche
	String tipo_errore="";//tipo di errore (piu` specifico di classe_errore)
	String classe_errore=""; //classe dell'errore (piu` generale di tipo_errore)
	
	if(session.getAttribute("nome")!= null) //controllo se l'utente ha fatto l'accesso
	{
		nome_sess = session.getAttribute("nome").toString(); //prendi attributo nome della sessione
		nome_sess = nome_sess.substring(0, 1).toUpperCase() + nome_sess.substring(1); //primo carattere maiuscolo

		cognome_sess = session.getAttribute("cognome").toString(); //prendi attributo cognome della sessione
		cognome_sess = cognome_sess.substring(0, 1).toUpperCase() + cognome_sess.substring(1); //primo carattere maiuscolo
		
		email_sess = session.getAttribute("email").toString(); //prendi attributo email della sessione
		email_sess = email_sess.toLowerCase(); //tutto minuscolo

		password_sess = session.getAttribute("password").toString(); //prendi attributo password della sessione
		
		accesso = is_logged_in(nome_sess); //controlla se ha fatto l'accesso
	}
	
	
	
	if(request.getParameter("page")!= null) //cambia pagina in base al parametro get
		pagina = request.getParameter("page"); //impostazione della pagina richiesta
	
		
	if(request.getParameter("error")!= null) //se viene rilevato un errore in una richiesta
	{
		String [] errore = base64ToString(request.getParameter("error")).split(","); //divisione del parametro errore
		//errore[0]=classe_errore; errore[1]=tipo_specifico_errore; errore[2]=pagina_di_arrivo
		classe_errore = errore[0];
		//out.print(classe_errore);
		switch(classe_errore)
		{
			case "sql": //errore sql
				pagina = stringToBase64(errore[2]); //ritorno alla pagina di errore
				tipo_errore = errore[1]; //tipo dell'errore dettagliato
				//out.print("errore: "+tipo_errore); 
			break;
			case "regex": //errore regex
				pagina = stringToBase64(errore[2]); //ritorno alla pagina di errore
				tipo_errore = errore[1]; //tipo dell'errore dettagliato 
				//out.print("errore: "+tipo_errore); 
			break;
			case "empty": //accesso fallito
				pagina = stringToBase64(errore[2]); //ritorno alla pagina di errore
				tipo_errore = errore[1]; //tipo dell'errore dettagliato 
				//out.print("errore: "+tipo_errore); 
			break;
			default:
		}
	}
	//out.print(accesso+"\n");
	
	
	
	//out.print(tipo_errore+"\n");
	//out.print(pagina+"\n");
	pagina = base64ToString(pagina); //conversione parametro get con la pagina
	//out.print(pagina);

      out.write("\r\n");
      out.write("<!-- Testa Navbar -->\r\n");
      out.write("<div class=\"img_bg\" style=\"background-image:url('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/background');\">\r\n");
      out.write("	<nav class=\"navbar navbar-expand-lg navbar-light \">\r\n");
      out.write("	\r\n");
      out.write("		<a class=\"navbar-brand mt-2 logo\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("			<img class=\"\" width=\"75px\" height=\"75px\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logo\" alt=\"Logo\"> \r\n");
      out.write("			<p><b>SIG</b>LOG</p>\r\n");
      out.write("		</a>\r\n");
      out.write("		\r\n");
      out.write("		<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("			<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("		</button>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"collapse navbar-collapse justify-content-end\" id=\"navbarNav\">\r\n");
      out.write("			");
if(accesso){ 
      out.write("\r\n");
      out.write("			<ul class=\"navbar-nav\">\r\n");
      out.write("				<li class=\"nav-item\">\r\n");
      out.write("					");
      out.print(email_sess);
      out.write("\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			<ul class=\"navbar-nav\">\r\n");
      out.write("				<li class=\"nav-item\">\r\n");
      out.write("					<a class=\"nav-link\" href=\"http://localhost:8080/Servlet_prova/index.jsp?page=");
      out.print(stringToBase64("profilo"));
      out.write("\">PROFILO</a>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			");
} else{ 
      out.write("\r\n");
      out.write("			<ul class=\"navbar-nav r-0\">\r\n");
      out.write("				<li class=\"nav-item\">\r\n");
      out.write("					<a class=\"nav-link\" href=\"http://localhost:8080/Servlet_prova/index.jsp?page=");
      out.print(stringToBase64("accedi"));
      out.write("\">ACCEDI </a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"nav-item\">\r\n");
      out.write("					<a class=\"nav-link\" href=\"http://localhost:8080/Servlet_prova/index.jsp?page=");
      out.print(stringToBase64("registra"));
      out.write("\">REGISTRATI</a>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			");
} 
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("	<!-- Corpo Pagina -->\r\n");
      out.write("	<div class=\"container-fluid corpo\" >\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col\"></div>\r\n");
      out.write("			<div class=\"centrale col-md-5 pt-2\" style=\"background-image:url('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/centrale\">\r\n");
      out.write("				");
if(pagina.equals("registra") && (!accesso || (tipo_errore !=""))){
      out.write("\r\n");
      out.write("					<!-- BLOCCO REGISTRAZIONE -->\r\n");
      out.write("					<form method=\"POST\" action=\"http://localhost:8080/Servlet_prova/registra\" >\r\n");
      out.write("						<p><b>REGISTRAZIONE</b></p>\r\n");
      out.write("						<hr>\r\n");
      out.write("						");
switch(classe_errore){
							case "sql":
      out.write("\r\n");
      out.write("						<div class=\"alert alert-danger alert-dismissible fade show d-flex justify-content-center\" role=\"alert\">\r\n");
      out.write("						    EMAIL' GIA REGISTRATA!\r\n");
      out.write("	      				</div>\r\n");
      out.write("						");
break;
							case "regex":
      out.write("\r\n");
      out.write("								<div class=\"alert alert-danger alert-dismissible fade show d-flex justify-content-center\" role=\"alert\">\r\n");
      out.write("							    ERRORE NELL'INSERIMENTO DEL PARAMETRO: ");
      out.print(tipo_errore.toUpperCase());
      out.write("\r\n");
      out.write("		      				</div>\r\n");
      out.write("						");
break;} 
      out.write("\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label for=\"nome\">Nome:</label>\r\n");
      out.write("							<input type=\"text\" class=\"form-control\" id=\"nome\" name=\"nome\" required>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label for=\"cognome\">Cognome:</label>\r\n");
      out.write("							<input type=\"text\" class=\"form-control\" id=\"cognome\" name=\"cognome\" required>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label for=\"email\">Email:</label>\r\n");
      out.write("							<input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" required>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label for=\"password\">Password:</label>\r\n");
      out.write("							<input type=\"password\" class=\"form-control\" id=\"password\" name=\"password\" placeholder=\"almeno 4 caratteri, una lettera maiuscola ed una minuscola\" required>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"bottoni\">\r\n");
      out.write("							<button type=\"submit\" class=\"btn btn-primary button_a\">Registrati</button>\r\n");
      out.write("						</div>\r\n");
      out.write("						<hr>\r\n");
      out.write("					</form>\r\n");
      out.write("					<div class=\"bottoni\">\r\n");
      out.write("						<div class=\"d-flex flex-column align-items-center\">\r\n");
      out.write("							<p>Hai gia' un account?</p>\r\n");
      out.write("							<button type=\"button\" class=\"btn btn-primary button_a\" ><a href=\"http://localhost:8080/Servlet_prova/index.jsp?page=");
      out.print(stringToBase64("accedi"));
      out.write("\">Accedi</a></button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				\r\n");
      out.write("				");
} else if(pagina.equals("accedi") && !accesso){ 
      out.write("\r\n");
      out.write("					<!-- BLOCCO ACCEDI -->\r\n");
      out.write("					<form method=\"POST\" action=\"http://localhost:8080/Servlet_prova/accedi\">\r\n");
      out.write("						<p><b>Accesso</b></p>\r\n");
      out.write("						<hr>\r\n");
      out.write("						");
switch(classe_errore){
							case "empty":
      out.write("\r\n");
      out.write("						<div class=\"alert alert-danger alert-dismissible fade show d-flex justify-content-center\" role=\"alert\">\r\n");
      out.write("						    ACCOUNT NON TROVATO\r\n");
      out.write("	      				</div>\r\n");
      out.write("						");
break;} 
      out.write("\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label for=\"email\">Email:</label>\r\n");
      out.write("							<input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" required>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label for=\"password\">Password:</label>\r\n");
      out.write("							<input type=\"password\" class=\"form-control\" id=\"password\" name=\"password\" required>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"bottoni\">\r\n");
      out.write("							<button type=\"submit\" class=\"btn btn-primary\">Accedi</button>\r\n");
      out.write("						</div>\r\n");
      out.write("						<hr>\r\n");
      out.write("						</form>\r\n");
      out.write("						<div class=\"bottoni\">\r\n");
      out.write("							<div class=\"d-flex flex-column align-items-center\">\r\n");
      out.write("								<p>Non hai ancora un account?</p>\r\n");
      out.write("								<button type=\"button\" class=\"btn btn-primary button_a\" ><a href=\"http://localhost:8080/Servlet_prova/index.jsp?page=");
      out.print(stringToBase64("registra"));
      out.write("\">Registrati</a></button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				");
 }else if(pagina.equals("profilo") && accesso){
      out.write("\r\n");
      out.write("			        <form method=\"POST\" action=\"http://localhost:8080/Servlet_prova/modifica\">\r\n");
      out.write("			        	<p><b>Modifica Profilo Utente</b></p>\r\n");
      out.write("			        	<hr>\r\n");
      out.write("			            <div class=\"form-group\">\r\n");
      out.write("			                <label for=\"nome\">Nome:</label>\r\n");
      out.write("			                <input type=\"text\" class=\"form-control\" id=\"nome\" name=\"nome\" value=\"");
      out.print(nome_sess);
      out.write("\" required>\r\n");
      out.write("			            </div>\r\n");
      out.write("			            <div class=\"form-group\">\r\n");
      out.write("			                <label for=\"cognome\">Cognome:</label>\r\n");
      out.write("			                <input type=\"text\" class=\"form-control\" id=\"cognome\" name=\"cognome\" value=\"");
      out.print(cognome_sess);
      out.write("\" required>\r\n");
      out.write("			            </div>\r\n");
      out.write("			            <div class=\"form-group\">\r\n");
      out.write("			                <label for=\"password\">Password:</label>\r\n");
      out.write("			                <input type=\"password\" class=\"form-control\" id=\"password\" name=\"password\" value=\"");
      out.print(password_sess);
      out.write("\" required>\r\n");
      out.write("			            </div>\r\n");
      out.write("			            <div class=\"form-group\" hidden>\r\n");
      out.write("							<label for=\"email\">Email:</label>\r\n");
      out.write("							<input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" value=\"");
      out.print(email_sess);
      out.write("\" required>\r\n");
      out.write("						</div>\r\n");
      out.write("			            <div class=\"bottoni\">\r\n");
      out.write("							<button type=\"submit\" class=\"btn btn-primary\">Salva modifiche</button>\r\n");
      out.write("						</div>\r\n");
      out.write("			        </form>\r\n");
      out.write("			        <div class=\"bottoni btn-group dropup\">\r\n");
      out.write("						<div class=\"spazio\"></div>\r\n");
      out.write("						<div class=\"dropdown-menu dropdown-menu-right\" aria-labelledby=\"conferma_elimina\">\r\n");
      out.write("							<p class=\"conferma\">SEI SICURO?</p>\r\n");
      out.write("							<a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/elimina\">Elimina account</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<button type=\"button\" class=\"btn btn-danger button_a\" data-toggle=\"dropdown\" aria-controls=\"conferma_elimina\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("							<a href=\"#\">Elimina</a>\r\n");
      out.write("						</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				");
 }else if(pagina.equals("entrato") || accesso){
      out.write("\r\n");
      out.write("					<!-- BLOCCO DI BENTORNATO/BENVENUTO -->\r\n");
      out.write("				    <div class=\"col mx-auto text-center\">\r\n");
      out.write("				      <h1>Ciao ");
      out.print(nome_sess);
      out.write("!</h1>\r\n");
      out.write("				      <p class=\"lead\">Grazie per aver effettuato l'accesso a SIGLOG.</p>\r\n");
      out.write("				      <p class=\"lead\">\r\n");
      out.write("				      	Siamo entusiasti di averti tra i nostri utenti <br> \r\n");
      out.write("				      	e siamo qui per aiutarti a sfruttare al massimo Siglog.<br>\r\n");
      out.write("				      	Ti auguriamo una buona permanenza e speriamo di rendere la tua esperienza con noi unica ed emozionante.<br>\r\n");
      out.write("				      	<br>	\r\n");
      out.write("						Con il tuo nuovo account, potrai accedere a contenuti personalizzati e servizi esclusivi.<br>\r\n");
      out.write("						Ti invitiamo ad esplorare Siglog<br>\r\n");
      out.write("						e a trovare tutte le funzionalita` che si adattano meglio alle tue esigenze.<br>\r\n");
      out.write("						Inizia subito ad usare il tuo account per accedere ai nostri servizi personalizzati.<br>\r\n");
      out.write("						<br>\r\n");
      out.write("						Se hai bisogno di aiuto o hai domande sul nostro sito o sui servizi che offriamo,<br>\r\n");
      out.write("						non esitare a contattarci.<br>\r\n");
      out.write("						Il nostro team di supporto e` a tua disposizione per rispondere a tutte le tue domande<br>\r\n");
      out.write("						e aiutarti in ogni modo possibile.<br>\r\n");
      out.write("						<br>\r\n");
      out.write("						Grazie ancora per aver scelto di unirti a noi.<br>\r\n");
      out.write("						Siamo impazienti di vedere cosa puoi fare con il tuo account<br>\r\n");
      out.write("						e di averti tra i nostri utenti piu' attivi ed entusiasti.<br>\r\n");
      out.write("						Buon divertimento!</p>\r\n");
      out.write("				      <button type=\"button\" class=\"btn btn-primary button_a\" ><a href=\"http://localhost:8080/Servlet_prova/index.jsp?page=");
      out.print(stringToBase64("esci"));
      out.write("\">Esci</a></button>\r\n");
      out.write("				    </div>\r\n");
      out.write("				\r\n");
      out.write("				");
} else{
      out.write("\r\n");
      out.write("					<div class=\"col mb-4 mx-auto text-center\">\r\n");
      out.write("						<div class=\"mt-4 d-flex flex-row justify-content-center\">\r\n");
      out.write("							<h1>Benvenuto in SIGLOG</h1>\r\n");
      out.write("					      	<img width=\"30px\" height=\"30px\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logo\" alt=\"Logo\">\r\n");
      out.write("					    </div>\r\n");
      out.write("					    <br>\r\n");
      out.write("				      <p class=\"lead\">Ciao e benvenuto nella nostra piattaforma</p>\r\n");
      out.write("				      <p class=\"lead\">\r\n");
      out.write("				      	Immagina di poter accedere a contenuti personalizzati e servizi esclusivi,<br>\r\n");
      out.write("				      	tutti al tuo servizio 24 ore al giorno. <br>\r\n");
      out.write("				      	Con Siglog, tutto questo e` possibile!<br>  \r\n");
      out.write("				      	<br>\r\n");
      out.write("				      	Inizia il tuo viaggio iscrivendoti.<br>\r\n");
      out.write("				      	Fornisci il tuo nome e l'indirizzo email per cominciare e scegli una password sicura,<br>\r\n");
      out.write("				      	cosi` potrai accedere facilmente ogni volta che vuoi.<br>\r\n");
      out.write("				      	<br>\r\n");
      out.write("						Una volta completata la registrazione, potrai finalmente accedere a Siglog.<br>\r\n");
      out.write("						Qui, potrai sfruttare appieno tutte le nostre funzionalita` personalizzate e le informazioni in esclusiva.<br>\r\n");
      out.write("						Immagina di poter gustare la bellezza delle nostre funzionalita`,<br>\r\n");
      out.write("						magari ascoltando una playlist personalizzata mentre sei seduto in un ambiente confortevole a casa.<br>\r\n");
      out.write("						O magari potresti usare la tua app preferita mentre sei immerso in una vasca da bagno calda e rilassante.<br>\r\n");
      out.write("						La scelta e` tua.<br>\r\n");
      out.write("						<br>\r\n");
      out.write("						E se deciderai che Siglog non fa al caso tuo, non c'e` problema: <br>\r\n");
      out.write("						puoi facilmente eliminare il tuo account seguendo le istruzioni sul sito. <br>\r\n");
      out.write("						Tuttavia, siamo certi che una volta provato, non potrai piu` farne a meno. <br>\r\n");
      out.write("						<br>\r\n");
      out.write("						Ti invitiamo a unirti a noi per un'esperienza unica e indimenticabile, <br>\r\n");
      out.write("						che non vedrai l'ora di condividere con i tuoi amici. Ti aspettiamo!</p>\r\n");
      out.write("				      <button type=\"button\" class=\"btn btn-primary button_a\" ><a href=\"http://localhost:8080/Servlet_prova/index.jsp?page=");
      out.print(stringToBase64("registra"));
      out.write("\">Registrati</a></button>\r\n");
      out.write("				    </div>\r\n");
      out.write("				");
} 
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Footbar -->\r\n");
      out.write("</div>\r\n");
      out.write("<footer class=\"footer bg-light mt-auto py-3\" style=\"background-image:url('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/nav');\">\r\n");
      out.write("	<div class=\"container text-center\">\r\n");
      out.write("		<span class=\"text-muted\">&copy; 2023 SigLog. Tutti i diritti riservati.</span>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<!-- js Bootstrap -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
